### ISSUE TITLE
Nested Group Support without AD

### ISSUE THREAD

**Issue by PhoenixIra** [scm-manager/scm-ldap-plugin#10]
## Issue description

Our current setup unfortunately requires nested groups on an OpenLDAP Server. Since OpenLDAP does not support native nested groups (in contrast to AD), we added support for nested members in the scm-ldap-plugin.

We would like to contribute this feature in order to reduce the work of maintaining our own folk. Would this feature fit into the plugin?

#### Problem to be solved

Most LDAP Server do not support nested groups (only AD does). In order to support nested groups, one way is to implement nested groups into the software accessing ldap servers.

#### Proposed solution

We already added the nested group feature into a fork of the plugin for version 1.60. We now would ask whether it is wished to add this feature into the main plugin. If this is the case, I would polish our current folk a bit more.

**Comment by pfeuffer** [comment]
We are always interested in community contributions. If you fear the cleanup without a good chance that we include you changes, maybe you can elaborate a bit more on your changes. How did you manage to build these nested groups inside SCM-Manager and what do you have to do in LDAP to achieve this? Sounds interesting for me, though I have to admit that I did not have to do a lot with LDAP up to now.

**Comment by PhoenixIra** [comment]
Let me elaborate it a bit more without assuming any knowledge about ldap at all:

ldap is a read-optimized database protocoll used commonly for modeling user organisation. ldap consists of entries (that are organized in a tree-directory form). Every entry is uniquely determined by their Distinguished Name (DN for short). You can query for entries using search filters. These entries can have different objectClasses and based on the objectClass attributes. Two common objectClasses are Users and GroupOfNames (although the names of these objectClases vary from server to server). This change mainly focuses on the second objectClass, the groups.

Groups have the attributes member (or a variation of this name). A member attribute stores just any DN. For our case, we store the DNs of Users in the member attributes of Groups.

This is also what the scm-ldap-plugin currently supports for servers that are not Active Directory.

However, there is no restriction to what we consider a member of a group. As such, it is common to include groups as members of groups. If a group is saved as a member of another group, we call this a nested group.


However, most (except for Active Directory) ldap servers don't know what a nested group is and as such, most ldap servers don't support search filter allowing recursively searching for nested groups (the operation is called ``LDAP_MATCHING_RULE_IN_CHAIN`` or ``:1.2.840.113556.1.4.1941:`` and is already supported by the scm-ldap-plugin but not by most ldap servers). 

Many ldap-plugins thus need to implement recursively searching nested groups themself.



Thus what I would change is the following:

- Add a method that iteratively applies the custom search filter entered in the scm-ldap-plugin setting on groups that the user is (up to now) member of until we reach a fixpoint (First method to fetch/get groups)
- Add a method that iteratively applies the memberOf search filter entered in the scm-ldap-plugin settings on groups that the user is (up to now) member of until we reach a fixpoint (Second method to fetch/get groups)
- Add an option in the scm-ldap-plugin settings to enable or disable recursively searching for nested groups
- Add a text space in the scm-ldap-plugin settings for the nested group search filter used by the first method.

Lastly let me include some arguments for and against it:

Pro:
- Nested Groups are very useful for system administrators
- Comparable ldap plugins (e.g. nextcloud ldap-app) also support nesting groups for non-AD servers
- The changes are optional and can be de/activated in the settings
- The changes are locally, it would only affect the settings and the class [LdapGroupResolver.java](https://github.com/scm-manager/scm-ldap-plugin/blob/develop/src/main/java/sonia/scm/auth/ldap/LdapGroupResolver.java), more precisely the methods fetchGroups (first method) and getGroups (second method).

Contra:
- recursively checking for nested group needs quadratic worst-time-complexity in the number of groups
- it involves two more non-trivial methods to maintain

**Comment by pfeuffer** [comment]
Hi @PhoenixIra ,

sorry for letting you wait so long. We currently have another issue with LDAP that leads to unnecessary requests, so we will have to take a look at this, no matter what.

We would love to include ideas and work from you and it sounds like a great idea. We cannot promise anything, though, but we will definitely take a look at it (and it will not take as long as this answer again). What would be great is a warning alongside the option you want to include, that this leads to more requests, so that a user will not be surprised. 

Thanks for your offer!

René
