### ISSUE TITLE
may include groups that are not of correct organization unit

### ISSUE THREAD

**Issue by PhoenixIra** [scm-manager/scm-ldap-plugin#14]
## Issue description

The ldap plugin includes groups that for which a user is memberOf, although it has a different organization unit. This seems to be a wrong behavior, however is actually asked like this in the junit tests.

### Bug Report

In `GroupResolverTest.shouldReturnGroupsFromAttribute` we ask for the groups of user trillian. The Junit Test expects this to be "HeartOfGold", "RestaurantAtTheEndOfTheUniverse" and "HappyVerticalPeopleTransporter". The config states that the organization unit for this server as `ou=Groups`. However, "HappyVerticalPeopleTransporter" is of the organization unit `ou=Other Groups` (compare test/ressources/ldif/006.ldif). I would not expect this behavior, especially as the group would **not** be inlcuded, if we would not use the 
`memberOf: cn=HappyVerticalPeopleTransporter,ou=Other Groups,dc=scm-manager,dc=org` attribute and instead use the 
`uniqueMember: uid=trillian,ou=People,dc=scm-manager,dc=org` attribute (compare test/ressources/ldif/007.ldif and `GroupResolverTest.shouldReturnGroupsFromSearch`).

Is this as intended?

#### Describe how to reproduce the bug

use memberOf attribute on an ldap server with a different organization unit

**Comment by pfeuffer** [comment]
Hi @PhoenixIra , my colleague developed a new option to exclude groups. Would you be so kind to check whether this resolves your issue? The new plugin has been released with [version 2.4.0](https://www.scm-manager.org/plugins/scm-ldap-plugin/releases/). Thank you!
