### ISSUE TITLE
LDAP Base Group OU doesn't work

### ISSUE THREAD

**Issue by helmut72** [scm-manager/scm-ldap-plugin#22]
## Issue description

Base Group OU doesn't work.

### Bug Report

When adding a Base Group OU (OU=Departments), all Groups not in this Base OU are also listed for the user when testing LDAP connection.

Group (OU): OU=Departments
Group Search Filter: (&(objectClass=group)(member={0}))

#### Describe how to reproduce the bug

Add a Base Group OU, test LDAP connection.

#### Describe your SCM-Manager setup

SCM-Manager as a Docker Container + LDAP Plugin

#### Which operating system, browser and versions do you use?

Docker on Ubuntu 20.04

**Comment by pfeuffer** [comment]
Would you be so kind to check whether this is the same issue described in #14, @helmut72 ?

**Comment by helmut72** [comment]
I guess he mean the same. One more example:

LDAP configuration:

CN=Finance,OU=Departments,DC=domain,DC=de
CN=Sales,OU=Departments,DC=domain,DC=de
CN=Other1,OU=Stuff,DC=domain,DC=de
CN=Other2,OU=Stuff,DC=domain,DC=de

user1 is member of Finance, Sales, Other1 and Other2

SCM-Manager configuration:
Group (OU): OU=Departments
Group Search Filter: (&(objectClass=group)(member={0}))

Behavior
Testing user1 shows all groups: Finance, Sale, Other1 and Other2

Expected Behavior because of Group (OU) setting: OU=Departments
Testing user1 shows Finance and Sales, because the base is OU=Departments

If there isn't OU=Departments set in Groups (OU), all Groups should be shown, because LDAP search from his root. But it could also be that I have misunderstood this setting.

**Comment by PhoenixIra** [comment]
It is not the exactly the same problem, but the same problem for a different method (#14 affects the Group Attribute Name Method, this affects the Group Search Filter Method)

**Comment by pfeuffer** [comment]
Hi @helmut72 , my colleague developed a new option to exclude groups. Would you be so kind to check whether this resolves your issue? The new plugin has been released with [version 2.4.0](https://www.scm-manager.org/plugins/scm-ldap-plugin/releases/). Thank you!
