### ISSUE TITLE
Invalid mail AD attribute makes the user unable to logon

### ISSUE THREAD

**Issue by folhabranca** [scm-manager/scm-ldap-plugin#6]
## Issue description

If the user has an e-mail registred but not in valid format at LDAP server, the user is unable to logon and the messages in log does not point to that.

In fact, the LdapAuthenticator class the authenticate method calls  authenticateUser method that logs the user was successfully authenticated but the createUser method called in sequence thows an InvalidUserException that only appear in log if configured in DEBUG mode. 

A better implementation would be to only set mail property of the user if it is in valid format allowing the logon to proceed and log a WARNING if not. 

#### Describe how to reproduce the bug

Just change the mail to an invalid format.

#### Describe your SCM-Manager setup

scmmanager 2.4.0 docker image with 2.0 LDAP plugin.

#### Which operating system, browser and versions do you use?

Windows browser.

**Comment by pfeuffer** [comment]
You are right, @folhabranca . We should find a way to handle these cases. Right now I'm just not sure, how. We will discuss this.

**Comment by folhabranca** [comment]
It has been a really long time that I've done something in Java, but if you allow me, here is one suggestion (probably will not compile):

original code:
user.setMail(LdapUtil.getAttribute(attributes, config.getAttributeNameMail()));

suggestion:
mail = LdapUtil.getAttribute(attributes, config.getAttributeNameMail());
if (!Util.isEmpty(mail)) {
    if  (ValidationUtil.isMailAddressValid(mail)) {
        user.setMail(mail);
    } else {
        logger.debug("The mail field for user {} is not valid. Ignoring it.", userDN);
    }
}

 if (!user.isValid()) {
      logger.debug("Not compatible user name: {}. Unable to log on", userDN);
      throw new InvalidUserException("invalid user object: " + user.toString(), user);
 }

**Comment by pfeuffer** [comment]
We released version 2.0.1 of the ldap plugin, which should fix your issues, @folhabranca .
